name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  go-fmt:
    name: go-fmt
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Checkout branch
        uses: actions/checkout@v3

      # Fail if go-fmt recommends any changes.
      - name: Run go fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

  go-test:
    name: go-test
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies if not found in cache.
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: go mod download && go install

      - name: Build package
        run: go build

      - name: Run go test
        run: go test -v ./
